uart:
  parity: ODD
  baud_rate: 19200

sensor:
  - platform: modbus_spy
    name: "Inside temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41200
    filters:
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
    on_raw_value:
      - script.execute:
          id: blink_light
          calling_component: Modbus
  - platform: modbus_spy
    name: "Domestic hot water temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41201
    filters:
      - filter_out: 3000
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Heating cooling temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41202
    filters:
      - filter_out: 3000
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Heat exchanger water outlet temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41203
    filters:
      - filter_out: 3000
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Heat exchanger water inlet temperature"
    id: heat_exchanger_water_inlet_temperature
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41204
    filters:
      - filter_out: 3000
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Indoor coil temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41205
    filters:
      - filter_out: 3000
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Heating cooling circuit 1 temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41208
    filters:
      - filter_out: 3000
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Heating cooling circuit 2 temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x0B
    register_address: 41209
    filters:
      - filter_out: 3000
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Internal pump speed state"
    state_class: "measurement"
    device_address: 0x0B
    register_address: 41304
    filters:
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Outdoor voltage"
    device_class: "voltage"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "V"
    device_address: 0x02
    register_address: 42101
    filters:
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Outdoor current"
    device_class: "current"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "A"
    device_address: 0x02
    register_address: 42102
    filters:
      - multiply: 0.1
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Compressor working speed setpoint"
    device_class: "frequency"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "Hz"
    device_address: 0x02
    register_address: 42103
    filters:
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Compressor working speed actual"
    device_class: "frequency"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "Hz"
    device_address: 0x02
    register_address: 42104
    filters:
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Outdoor fan setpoint"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "rpm"
    device_address: 0x02
    register_address: 42105
    filters:
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Outdoor fan 1 actual"
    accuracy_decimals: 0
    state_class: "measurement"
    unit_of_measurement: "rpm"
    device_address: 0x02
    register_address: 42106
    filters:
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Expansion valve setting"
    state_class: "measurement"
    device_address: 0x02
    register_address: 42108
    filters:
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Ambient temperature"
    id: ambient_temperature
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x02
    register_address: 42111
    filters:
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
    on_raw_value:
      - script.execute:
          id: blink_light
          calling_component: Modbus
  - platform: modbus_spy
    name: "Outdoor coil temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x02
    register_address: 42112
    filters:
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Discharge temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x02
    register_address: 42113
    filters:
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Suction temperature"
    device_class: "temperature"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_address: 0x02
    register_address: 42114
    filters:
      - offset: -3000
      - multiply: 0.01
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "Low pressure"
    device_class: "pressure"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "bar"
    device_address: 0x02
    register_address: 42117
    filters:
      - multiply: 0.1
      - throttle: ${throttling_value}
  - platform: modbus_spy
    name: "High pressure"
    device_class: "pressure"
    accuracy_decimals: 1
    state_class: "measurement"
    unit_of_measurement: "bar"
    device_address: 0x02
    register_address: 42118
    filters:
      - multiply: 0.1
      - throttle: ${throttling_value}
  - platform: modbus_spy
    id: defrost_value1
    device_address: 0x02
    register_address: 42109
  - platform: modbus_spy
    id: defrost_value2
    device_address: 0x02
    register_address: 42119
  - platform: modbus_spy
    id: defrost_value3
    device_address: 0x02
    register_address: 42120


binary_sensor:
  - platform: modbus_spy
    name: "Pump 1 active"
    device_address: 0x0B
    register_address: 41301
  - platform: modbus_spy
    name: "Pump 2 active"
    device_address: 0x0B
    register_address: 41302
  - platform: modbus_spy
    name: "Domestic hot water pump active"
    device_address: 0x0B
    register_address: 41303
  - platform: modbus_spy
    name: "Internal pump active"
    device_address: 0x0B
    register_address: 41213
  - platform: modbus_spy
    name: "Heating switch"
    icon: "mdi:fire"
    device_address: 0x0B
    register_address: 41215
  - platform: modbus_spy
    name: "Three way valve state"
    device_address: 0x0B
    register_address: 41306
  - platform: modbus_spy
    name: "Internal auxilliary heater"
    icon: "mdi:flash"
    device_address: 0x0B
    register_address: 41310